services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=appointmentBookings'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '54321:5432'
