spring:
  datasource:
    url: ${CUSTOMCONNSTR_DBConnection}
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      format_sql: false
